### ISSUE TITLE
urllib3 2.2.2 not compatible with python 3.7

### ISSUE THREAD

**Issue by AaronOpfer** [conda-forge/urllib3-feedstock#84]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Upstream broke Python 3.7 support. Recommend changing recipe to `python >= 3.8` and patching repodata.
```
$ python -c 'import urllib3.contrib.socks'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ctc/users/opfera/.conda/testenv/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 75, in <module>
    class _TYPE_SOCKS_OPTIONS(typing.TypedDict):
AttributeError: module 'typing' has no attribute 'TypedDict'
```

### Installed packages

```shell
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotli-python             1.0.9            py37hd23a5d3_7    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0              h77fa898_11    conda-forge
libgomp                   13.2.0              h77fa898_11    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              13.2.0              hc0a3c3a_11    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python_abi                3.7                     4_cp37m    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : testenv
    active env location : <privacy snip>
            shell level : 2
       user config file : <privacy snip>
 populated config files : /etc/conda/condarc
                          <privacy snip>
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.10.12.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.5.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : <privacy snip>  (writable)
      conda av data dir : <privacy snip>
  conda av metadata url : None
           channel URLs : <privacy snip>
          package cache : <privacy snip>
                          <privacy snip>
       envs directories : <privacy snip>
                          <privacy snip>
                          <privacy snip>
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.12 Linux/3.10.0-1160.114.2.el7.x86_64 rhel/7.9 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : <privacy snip>
             netrc file : None
           offline mode : False
```

**Comment by AaronOpfer** [comment]
@pquentin thanks for addressing this issue. Can you also make a repodata patch if you have the time?

**Comment by AaronOpfer** [comment]
@ocefpaf I attempted to write a repodata patch myself, but `show_diff.py` suggests it is ineffective.
```yaml
# https://github.com/conda-forge/urllib3-feedstock/issues/84
# urllib3 2.2.2 is not compatible with Python 3.7
if:
  name: invoke
  version: 2.2.2
  timestamp_lt: 1719424349134  # 2024/06/26 12:52 GMT
then:
  - replace_depends:
      old: python >=3.7
      new: python >=3.8
```

I also tried this, and it didn't seem to work either.

```yaml
# https://github.com/conda-forge/urllib3-feedstock/issues/84
# urllib3 2.2.2 is not compatible with Python 3.7
if:
  name: invoke
  version_eq: 2.2.2
  timestamp_lt: 1718841600  # 2024/06/20 00:00Z
then:
  - tighten_depends:
      name: python
      lower_bound: 3.8
```
